apiVersion: v1
kind: ConfigMap
metadata:
  name: artifacts-config
  namespace: spinnaker
data:
  custom-object.json: |-
    {
      "name": "custom-artifact",
      "types": [
        "custom/object"
      ]
    }
  docker-image.json: |-
    {
      "name": "docker-registry",
      "types": [
        "docker/image"
      ]
    }
  embedded-base64.json: |-
    {
      "name": "embedded-artifact",
      "types": [
        "embedded/base64"
      ]
    }
  front50-pipeline-template.json: |-
    {
      "name": "front50ArtifactCredentials",
      "types": [
        "front50/pipelineTemplate"
      ]
    }
  gcs-object.json: |-
    {
      "name": "onboarding-pub-sub",
      "types": [
        "gcs/object"
      ]
    }
  git-repo.json: |-
    {
      "name": "github-spinnaker",
      "types": [
        "git/repo"
      ]
    }
  github-file.json: |-
    {
      "name": "github.com",
      "types": [
        "github/file"
      ]
    }
  helm-chart-stable.json: |-
    {
      "name": "helm-stable",
      "types": [
        "helm/chart"
      ],
      "url": "https://kubernetes-charts.storage.googleapis.com"
    }
  http-file.json: |-
    {
      "name": "http",
      "types": [
        "http/file"
      ]
    }
  kubernetes.json: |-
    {
      "name": "kubernetes",
      "types": [
        "kubernetes/configMap",
        "kubernetes/deployment",
        "kubernetes/replicaSet",
        "kubernetes/secret"
      ]
    }
  no-auth-http-file.json: |-
    {
      "name": "no-auth-http-account",
      "types": [
        "http/file"
      ]
    }
